name: 'Migrated Script'
description: 'A script that sets random configurations and runs evomaster'
outputs:
  feedbackDirectedSampling:
    description: 'Random feedbackDirectedSampling configuration'
  probOfApplySQLActionToCreateResources:
    description: 'Random probOfApplySQLActionToCreateResources configuration'
  probOfRandomSampling:
    description: 'Random probOfRandomSampling configuration'
  baseTaintAnalysisProbability:
    description: 'Random baseTaintAnalysisProbability configuration'
  focusedSearchActivationTime:
    description: 'Random focusedSearchActivationTime configuration'
runs:
  using: 'composite'
  steps:
    - name: Set permissions for evomaster.jar
      shell: bash
      run: chmod +rx evomaster.jar
    
    - name: Obtener una configuración aleatoria
      id: obtener-configuracion
      shell: bash
      run: |
        CONFIGURACION=$(shuf -n 1 .feedbackDirectedSampling)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=feedbackDirectedSampling::$CONFIGURACION"

        CONFIGURACION=$(shuf -n 1 .probOfApplySQLActionToCreateResources)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=probOfApplySQLActionToCreateResources::$CONFIGURACION"
        
        CONFIGURACION=$(shuf -n 1 .probOfRandomSampling)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=probOfRandomSampling::$CONFIGURACION"
        
        CONFIGURACION=$(shuf -n 1 .baseTaintAnalysisProbability)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=baseTaintAnalysisProbability::$CONFIGURACION"

        CONFIGURACION=$(shuf -n 1 .focusedSearchActivationTime)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=focusedSearchActivationTime::$CONFIGURACION"
      
    - name: Run evomaster
      shell: bash
      run: java -jar evomaster.jar --blackBox true --bbSwaggerUrl https://api.apis.guru/v2/openapi.yaml --outputFormat JAVA_JUNIT_4 --maxTime 30s --ratePerMinute 60 --feedbackDirectedSampling ${{ steps.obtener-configuracion.outputs.feedbackDirectedSampling }} --probOfApplySQLActionToCreateResources ${{ steps.obtener-configuracion.outputs.probOfApplySQLActionToCreateResources }} --probOfRandomSampling ${{ steps.obtener-configuracion.outputs.probOfRandomSampling }} --baseTaintAnalysisProbability ${{ steps.obtener-configuracion.outputs.baseTaintAnalysisProbability }} --focusedSearchActivationTime ${{ steps.obtener-configuracion.outputs.focusedSearchActivationTime }}