name: 'Migrated Script'
description: 'A script that sets random configurations and runs evomaster'
outputs:
  feedbackDirectedSampling:
    description: 'Random feedbackDirectedSampling configuration'
  probOfApplySQLActionToCreateResources:
    description: 'Random probOfApplySQLActionToCreateResources configuration'
  probOfRandomSampling:
    description: 'Random probOfRandomSampling configuration'
  baseTaintAnalysisProbability:
    description: 'Random baseTaintAnalysisProbability configuration'
  focusedSearchActivationTime:
    description: 'Random focusedSearchActivationTime configuration'
runs:
  using: 'composite'
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set permissions for evomaster.jar
      shell: bash
      run: chmod +rx ${{ github.action_path }}/evomaster.jar
    
    - name: Obtener una configuración aleatoria
      id: obtener-configuracion
      shell: bash
      run: |
        CONFIGURACION=$(shuf -n 1 ${{ github.action_path }}/.feedbackDirectedSampling)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=feedbackDirectedSampling::$CONFIGURACION"

        CONFIGURACION=$(shuf -n 1 ${{ github.action_path }}/.probOfApplySQLActionToCreateResources)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=probOfApplySQLActionToCreateResources::$CONFIGURACION"
        
        CONFIGURACION=$(shuf -n 1 ${{ github.action_path }}/.probOfRandomSampling)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=probOfRandomSampling::$CONFIGURACION"
        
        CONFIGURACION=$(shuf -n 1 ${{ github.action_path }}/.baseTaintAnalysisProbability)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=baseTaintAnalysisProbability::$CONFIGURACION"

        CONFIGURACION=$(shuf -n 1 ${{ github.action_path }}/.focusedSearchActivationTime)
        echo "Configuración seleccionada: $CONFIGURACION"
        echo "::set-output name=focusedSearchActivationTime::$CONFIGURACION"
      
    - name: Run evomaster
      shell: bash
      run: java -jar ${{ github.action_path }}/evomaster.jar --blackBox true --bbSwaggerUrl https://api.apis.guru/v2/openapi.yaml --outputFormat JAVA_JUNIT_4 --maxTime 30s --ratePerMinute 60 --feedbackDirectedSampling ${{ steps.obtener-configuracion.outputs.feedbackDirectedSampling }} --probOfApplySQLActionToCreateResources ${{ steps.obtener-configuracion.outputs.probOfApplySQLActionToCreateResources }} --probOfRandomSampling ${{ steps.obtener-configuracion.outputs.probOfRandomSampling }}        --baseTaintAnalysisProbability ${{ steps.obtener-configuracion.outputs.baseTaintAnalysisProbability }}        --focusedSearchActivationTime ${{ steps.obtener-configuracion.outputs.focusedSearchActivationTime }}


    - name: Checkout code
      uses: actions/checkout@v2


    - name: ls
      shell: bash
      run: ls

    - name: Install jq
      shell: bash
      run: sudo apt-get install jq

    - name: Generate Markdown Table
      shell: bash
      run: |
        echo "| Variable  | Value|" 
        echo "|----------|----------|" 
        echo "| feedbackDirectedSampling | ${{ steps.obtener-configuracion.outputs.feedbackDirectedSampling }} |"
        echo "| probOfApplySQLActionToCreateResources | ${{ steps.obtener-configuracion.outputs.probOfApplySQLActionToCreateResources }} |"
        echo "| probOfRandomSampling | ${{ steps.obtener-configuracion.outputs.probOfRandomSampling }} |"
        echo "| baseTaintAnalysisProbability | ${{ steps.obtener-configuracion.outputs.baseTaintAnalysisProbability }} |"
        echo "| focusedSearchActivationTime | ${{ steps.obtener-configuracion.outputs.focusedSearchActivationTime }} |"